services:
  task:
    image: ivshvl/dockerhub:finaltask7
    restart: always
    environment:
      DBHOST: db
      DBPORT: 5432
      DBNAME: TaskDB
    ports:
      - 8088:8080
    links:
      - "db"

  db:
    container_name: postgres_container
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: TaskDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
