create TABLE users(
                      id int GENERATED BY DEFAULT as identity PRIMARY KEY ,
                      username varchar(100) not null,
                      password varchar(100) not null,
                      email varchar(100) not null unique
);
create TABLE tasks(
                      id int GENERATED BY DEFAULT as identity PRIMARY KEY ,
                      header varchar(100) not null ,
                      description varchar(100) not null,
                      status varchar(15) not null,
                      author_id int references users(id) on DELETE SET NULL,
                      executor_id int references users(id) on DELETE SET NULL,
                      created_at timestamp
);
create TABLE comments(
                         id int GENERATED BY DEFAULT as identity PRIMARY KEY ,
                         text varchar(100) not null ,
                         author_id int references users(id) on DELETE SET NULL,
                         created_at timestamp,
                         task_id int references tasks(id) on DELETE SET NULL
);
create table roles (
                       id                    int GENERATED BY DEFAULT as identity PRIMARY KEY,
                       name                  varchar(50) not null
);
CREATE TABLE users_roles (
                             user_id               bigint not null,
                             role_id               int not null,
                             primary key (user_id, role_id),
                             foreign key (user_id) references users (id),
                             foreign key (role_id) references roles (id)
);
